services:
- docker
env:
  global:
  - TERM=dumb
  - DOCKER_USERNAME=daggerok
  - DOCKER_IMAGE_NAME=jboss-eap-6.4
  - secure: tGY8UOoEl/vybLj8qBHJLb5YdoZT1l/MqvqsJr2SN/q8As8Mtbnlhj6n30Bq7Insq0imvGJqtXRqOR4o/3XS+lJhYL4gN5Ysx0orvEFktiFDDKR/kugqkQDnEzKslwm9fr5bxjQvSj8tsyKkCSHEZ8GfjxKVExEJBZMrMXn+ppmOtynG8GnswwqUvqMU5+YbMxv8ZnVAhzQoJI73q86stPsYwCtovCsw9TkF5hgXhb738okR7PI2BHs35p5sdaql08gKASJV14S017az2Gh8W0iN3T547qF2PssoJPqEskz3Hpe4zx14a2kH9TQNbYNT36ZtAtzPCUKWqMpbeE+YeRWNiKmUptkdRxX5H6jzhyjcuIMWLkblvR+Q2iGD2gEkJtwV29jcupVzbYAJDvPjqAttrlPZLaZlj90V46SK/OVZIZXvYtcFUV7bNYtmhhLN3TR9Yfjq3QNr/FS4jU7TOo2SHkb4+Vr9pqr1vUSICwDSXtMdSAPzdUdUGdRXII9eWOQPXgVAgZ6Ifa/QDnO0NSDhigZyzLimS/3IduU0orHzBl2NxKy5Q3jGT5+UneoFBVvBEb92g4M/O7LOxotz422GSd49LRicNbFL3eOYANCbp0DrZWBfw0L7sxLCDWYAiEyuI46AO7PF2fDM5AH/rXljDitUHYuuLiDPfIBDVbo=
script:
- docker build -t ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} .
- |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:alpine
  else
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}-alpine
  fi
- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
- docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}
